from enum import Enum

class DebtState(str, Enum):
    CLEAR = "CLEAR"
    SUSPECTED = "SUSPECTED"
    CONFIRMED_DEBT = "CONFIRMED_DEBT"
    INTERVENTION_PROPOSED = "INTERVENTION_PROPOSED"
    MENTOR_REVIEW = "MENTOR_REVIEW"
    IN_INTERVENTION = "IN_INTERVENTION"
    FOLLOW_UP = "FOLLOW_UP"
    VERIFYING = "VERIFYING"
    REPAID = "REPAID"
    FAILED = "FAILED"
    NEW_INTERVENTION = "NEW_INTERVENTION"
    ESCALATED = "ESCALATED"
    REGRESSED = "REGRESSED"
