"""initial knowledge debt schema

Revision ID: 9efe46230780
Revises: 
Create Date: 2026-09-19 12:29:43.400630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efe46230780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_name'), ['name'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_external_id'), ['external_id'], unique=True)

    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CLEAR', 'SUSPECTED', 'CONFIRMED_DEBT', 'INTERVENTION_PROPOSED', 'MENTOR_REVIEW', 'IN_INTERVENTION', 'FOLLOW_UP', 'VERIFYING', 'REPAID', 'FAILED', 'ESCALATED', 'REGRESSED', name='debt_status', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='debt_severity', native_enum=False), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failed_interventions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'concept_id', name='uq_debt_student_concept')
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index('ix_debt_student_concept', ['student_id', 'concept_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('quiz', 'coding', 'follow_up', 'leetcode', name='evidencesource', native_enum=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_student_concept', ['student_id', 'concept_id'], unique=False)

    op.create_table('prerequisites',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('concept_id', 'prerequisite_concept_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_debt_id', ['debt_id'], unique=False)
        batch_op.create_index('ix_events_student_id', ['student_id'], unique=False)

    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=8), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('mentor_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debt_id', 'version', name='uq_intervention_debt_version')
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index('ix_interventions_debt_id', ['debt_id'], unique=False)

    op.create_table('mentor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('edited_content', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_mentor_reviews_intervention_id', ['intervention_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_mentor_reviews_intervention_id')

    op.drop_table('mentor_reviews')
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_index('ix_interventions_debt_id')

    op.drop_table('interventions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_student_id')
        batch_op.drop_index('ix_events_debt_id')

    op.drop_table('events')
    op.drop_table('prerequisites')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_student_concept')

    op.drop_table('evidence')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index('ix_debt_student_concept')

    op.drop_table('debts')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_external_id'))

    op.drop_table('students')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_name'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
